# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: sarkari-naukari
  labels:
    app: sarkari-naukari
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: sarkari-naukari
  type: ClusterIP