apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sarkari-naukari
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rentro.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sarkari-naukari
            port:
              number: 8000