name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: build
        run: go build -o sarkari-naukari

      - name: Test
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2
          
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses  : docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DDOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sarkari-naukari:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: update tag in helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/sarkari-naukari-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "abhishekp0084@gmail.com"
          git config --local user.name "abhishekp084"
          git add helm/sarkari-naukari-chart/values.yaml
          git commit -m "Update tag in helm chart"
          git push


